各種ブロックのリファクタリング
vektor-inc/vk-filter-search pull request #76
Opened 2021-01-18 05:44 UTC by drill-lancer

リファクタリングは終わったのですが、なぜか編集画面にブロックが表示されません。

2021-01-19 01:36 UTC, drill-lancer commented
ビルド系は解決しました。
単に JS 側でブロックを登録する関数が走ってなかっただけっぽいです。
ついでに 編集画面の CSS も調整しました。( useBlockProps の影響 )

2021-02-09 02:47 UTC, miminari requested changes
ブランチでテストを開始して、プラグインを追加したら、ReactのWarningが1件でます。
masterブランチでも同様のWarningが出るようです。
まずはこのWaringの調査から入られるのが良いかなと思ったのですがいかがでしょう？
```
Warning: Cannot update a component (`UnsavedChangesWarning`) while rendering a different component (`edit`). To locate the bad setState() call inside `edit`, follow the stack trace as described in 
```

2021-02-09 03:01 UTC, miminari commented
すみません、確認環境の情報書いてなかったです、
WordPress 5.6.1
Theme : Twenty Twenty One
ブラウザは Chrome　バージョン: 88.0.4324.146（Official Build） （x86_64）
Safari がバージョン14.0.2 (15610.3.7.1.10, 15610)
Mac OS: 10.15.7

2021-02-09 06:14 UTC, drill-lancer commented
@miminari 
修正しておきました。
何回もレビューしていただくのも時間がかかるのでこのブランチにまとめておきました。

2021-02-09 09:21 UTC, miminari commented
@drill-lancer ローカルでテストして、waring出ないことを確認しました！修正ありがとうございます。

2021-02-09 13:53 UTC, kurudrive approved these changes

2021-02-10 00:43 UTC, merged